/** @type {import('tailwindcss').Config} */

module.exports = {
    content: ['./src/**/*.{js,ts,jsx,tsx}'],
    darkMode: ['class'],
    theme: {
        extend: {
            colors: {
                gray: {
                    20: '#ececf1',
                    50: '#f7f7f8',
                    100: '#ececec',
                    200: '#e3e3e3',
                    300: '#cdcdcd',
                    400: '#999696',
                    500: '#595959',
                    600: '#424242',
                    700: '#2f2f2f',
                    800: '#212121',
                    850: '#171717',
                    900: '#0d0d0d',
                },
                green: {
                    50: '#f1f9f7',
                    100: '#def2ed',
                    200: '#a6e5d6',
                    300: '#6dc8b9',
                    400: '#41a79d',
                    500: '#10a37f',
                    550: '#349072',
                    600: '#126e6b',
                    700: '#0a4f53',
                    800: '#06373e',
                    900: '#031f29',
                },
                'brand-purple': 'var(--brand-purple)',
                presentation: 'var(--presentation)',
                'text-primary': 'var(--text-primary)',
                'text-secondary': 'var(--text-secondary)',
                'text-secondary-alt': 'var(--text-secondary-alt)',
                'text-tertiary': 'var(--text-tertiary)',
                'text-warning': 'var(--text-warning)',
                'ring-primary': 'var(--ring-primary)',
                'header-primary': 'var(--header-primary)',
                'header-hover': 'var(--header-hover)',
                'header-button-hover': 'var(--header-button-hover)',
                'surface-active': 'var(--surface-active)',
                'surface-active-alt': 'var(--surface-active-alt)',
                'surface-hover': 'var(--surface-hover)',
                'surface-hover-alt': 'var(--surface-hover-alt)',
                'surface-primary': 'var(--surface-primary)',
                'surface-primary-alt': 'var(--surface-primary-alt)',
                'surface-primary-contrast': 'var(--surface-primary-contrast)',
                'surface-secondary': 'var(--surface-secondary)',
                'surface-secondary-alt': 'var(--surface-secondary-alt)',
                'surface-tertiary': 'var(--surface-tertiary)',
                'surface-tertiary-alt': 'var(--surface-tertiary-alt)',
                'surface-dialog': 'var(--surface-dialog)',
                'surface-submit': 'var(--surface-submit)',
                'surface-submit-hover': 'var(--surface-submit-hover)',
                'surface-destructive': 'var(--surface-destructive)',
                'surface-destructive-hover': 'var(--surface-destructive-hover)',
                'surface-chat': 'var(--surface-chat)',
                'border-light': 'var(--border-light)',
                'border-medium': 'var(--border-medium)',
                'border-medium-alt': 'var(--border-medium-alt)',
                'border-heavy': 'var(--border-heavy)',
                'border-xheavy': 'var(--border-xheavy)'
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
        },
    },
    plugins: [
        require('tailwindcss-animate'),
        require('tailwindcss-radix'),
    ],
}
